apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-processor-deployment 
  labels:
    app: notifications-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-processor
  template:
    metadata:
      labels:
        app: notifications-processor
    spec:
      containers:
      - name: notifications-processor
        image: notifications-event-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Development"
        - name: RabbitMq__Host
          valueFrom:
            configMapKeyRef:
              name: notifications-config
              key: RabbitMq__Host
        - name: RabbitMq__UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password