apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  type: LoadBalancer 
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 3000       
      targetPort: 8080