apiVersion: v1
kind: Service
metadata:
  name: notifications-processor
spec:
  type: ClusterIP
  selector:
    app: notifications-processor
  ports:
    - name: processor
      protocol: TCP
      port: 8080
      targetPort: 8080
